### ISSUE TITLE
Notes when building the package

### ISSUE THREAD

**Issue by mdozmorov** [stilianoudakis/preciseTAD#1]
Not critical, but check if possible to fix

````
> checking package dependencies ... NOTE
  Package suggested but not available for checking: ‘BiocCheck’

> checking installed package size ... NOTE
    installed size is  5.4Mb
    sub-directories of 1Mb or more:
      data   4.2Mb

> checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘ToDo.md’

> checking dependencies in R code ... NOTE
  There are ::: calls to the package's namespace in its code. A package
    almost never needs to use ::: for its own objects:
    ‘hg19’
````

**Comment by stilianoudakis** [comment]
> checking package dependencies ... NOTE
  Package suggested but not available for checking: ‘BiocCheck’

This required me to copy the BiocCheck batch file in the BiocCheck\script folder to the my R\R-4.0.1\bin folder. I don't receive this note on my end

> checking installed package size ... NOTE
    installed size is  5.4Mb
    sub-directories of 1Mb or more:
      data   4.2Mb

Will address if Bioconductor complains. It's just over the 5Mb limit. Not sure if they are sticklers for this

> checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘ToDo.md’

Can't find this file on my end. I don't receive this note

> checking dependencies in R code ... NOTE
  There are ::: calls to the package's namespace in its code. A package
    almost never needs to use ::: for its own objects:
    ‘hg19’

I use this data to set chromosome lengths it is stored in R\sysdata.rda. I was not able to load it properly when using "::". I'll investigate if there is a better way

**Comment by mdozmorov** [comment]
Out of the above, the `:::` issue sounds important. Rda files suppose to be in the `data` folder, documented and called as usual, no?

**Comment by stilianoudakis** [comment]
So i used the source in creating the rda (section 12.2 Internal data):

https://r-pkgs.org/data.html

Then it was unclear how to appropriately call in the data in a function. For that I found this (answer at the bottom):

https://stackoverflow.com/questions/32964741/accessing-sysdata-rda-within-package-functions

If they complain, an alternative would be to just create the data frame in the function

**Comment by mdozmorov** [comment]
Got it, and it is correct - internal, non-exported objects are accessed with `:::`. Closing as non-critical, and we can reopen if needed.
