### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by mdozmorov** [stilianoudakis/preciseTAD#10]
Can pre-trained models be provided? For Gm12878, K562 and possible others. Perhaps, trained on Arrowhead and Peakachu boundaries, to allow one to predict TAD or loop boundaries.

**Comment by stilianoudakis** [comment]
It will be difficult given the memory limitations. For example a model training on CHR1-CHR21 and tested on CHR22 using arrowhead bounds at 5kb is ~400,000Kb of memory

**Comment by mdozmorov** [comment]
Yes, this is why you can train a model on a cluster that resources for it, save it as an .rda object, and provide to be reused. This is a critical missing part of the results and the package.

**Comment by stilianoudakis** [comment]
addressed
