### ISSUE TITLE
Put to dozmorovlab

### ISSUE THREAD

**Issue by mdozmorov** [stilianoudakis/preciseTAD#3]
Put the package on dozmorovlab account and associate this repo with BioC submission. Keep pushing to both yours and dozmorovlab repos

Change installation instructions in the vignette to specify dozmorovlab installation as the release version and stilianoudakis repo as the development version.

**Comment by stilianoudakis** [comment]
Sure thing. Do I need permission from the dozmorovlab account first to add repo?

**Comment by mdozmorov** [comment]
Just send the invite. Not sure why it wasn't done earlier

**Comment by stilianoudakis** [comment]
pushed to dozmorovlab

**Comment by mdozmorov** [comment]
Just make sure to push to both repos. Check something like https://articles.assembla.com/en/articles/1136998-how-to-add-a-new-remote-to-your-git-repo

**Comment by mdozmorov** [comment]
Add "About" description on GitHub page, like it is now in your repo

**Comment by mdozmorov** [comment]
Need to redo. You do NOT create new repository, just add new remote URL to your existing repository and push to the new URL. As of now, they are disjoint and cannot be pushed to simultaneously. 

Delete the current dozmorovlab repo, make new, add new remote URL to it, set it as default. Just don't forget pushing to your repo as well.

**Comment by stilianoudakis** [comment]
Okay. But this still requires initially creating a new repo on dozmorovlab right? So that I can use the url in "git remote add <repo url on dozmorovlab>" command?

**Comment by mdozmorov** [comment]
Yes. You just need to add the new URL to your existing repo, and push there

**Comment by stilianoudakis** [comment]
Okay should be good to go now

**Comment by mdozmorov** [comment]
It works now. Make sure to push to both, and watch both - I'll be pushing and opening issues in dozmorovlab repo
