### ISSUE TITLE
Vignette clarifications

### ISSUE THREAD

**Issue by mdozmorov** [stilianoudakis/preciseTAD#8]
Specify early on in the vignette that all coordinates are hg19 - correct?

Write legend for Figure 1

"To format `preciseTAD` results to use in juicebox, set `juicer=FALSE`." - Shouldn't be true?

The sentence 
````
From the results above we see that *ARROWHEAD* yielded 18 called TAD boundary points (CTBP). However, `preciseTAD` yielded 13 precise TAD boundary points (PTBP). The corresponding predicted TAD boundary regions (PTBR) that flank each PTBP are also provided. 
````
introduces CTBP. It creates an illusion that ARROWHEAD is being run, and "yields" some results. Clarify it is not. Define CTBP and other abbreviations in the function's help.

**Comment by stilianoudakis** [comment]
added clarification in both vignette and help section of function

**Comment by stilianoudakis** [comment]
added legend to fig1

**Comment by mdozmorov** [comment]
Reviewed, closing now, will need to proof-read the whole vignette again
